### ISSUE TITLE
Setting Up?

### ISSUE THREAD

**Issue by oleteacher** [davismcphee/drive-blog#1]
Very interesting and like the idea very much.

Just not sure how to setup? Where do you enter info to pull content from Gdrive? Can you pull content from certain folder on Gdrive?

This may be perfect for simple classroom blogs since most all have a google account through school email.

Thanks!

**Comment by coldes** [comment]
...yes agree as per above, so why release a "plugin" with no instructions on how to setup/implement?

**Comment by davismcphee** [comment]
Apologies for the lack of documentation. The project was in an unfinished state until today, and I now have a stable release. Documentation will be available ASAP, so stay tuned and thanks for the interest!

**Comment by oleteacher** [comment]
No problem @davismcphee. Thank you for sharing your drive blog project, will come in real handy!

Looking forward to seeing your final setup.

**Comment by davismcphee** [comment]
Thanks for the patience! There is now documentation on setup and usage in the readme. Hope you enjoy.

**Comment by coldes** [comment]
..thank you, however, have set this up in a codepen, tested it works OK
using your credentials, then reset with my apiKey and folderId and no luck,
in my GDrive folder [shared] I have a GDrive Doc with added text:
---------------------------
<->
title: TEST
subtitle: Does this work?
<->
(image)(test-image.jpg)

-------------------------------
plus uploaded a markdown file also with the above snippet

nothing is working, what I do not get clear from your github is exactly how
a GDrive file should be formatted, if you could provide a sample file I
feel that will help "join the dots"

Any assistance will be appreciated

**Comment by davismcphee** [comment]
I'm sorry, in my rush to get documentation up, I accidentally linked to the wrong API. So the API key was likely the issue. I've updated the readme with the proper API key instructions now. Hope it works for you!

**Comment by coldes** [comment]
...I already had the API Key, even though your first link went to Google
maps api, I have other api's, so new how to get a GDrive api, HOWEVER I had
restriction set as referrer, so reset to None and all works OK, thank you
